import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import "../app/globals.css";
import type { ReactNode } from "react";
import Image from "next/image";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "M.FK Portfolio",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${font.className} min-h-screen flex flex-col`}>
        <header className="bg-black text-white p-4 w-full">
          <nav className="container mx-auto flex flex-wrap items-center justify-between">
            <div className="flex items-center space-x-4">
              <Image 
                src="/images/M.fk Logo.png"
                alt="Logo" 
                width={30} 
                height={20} 
                className="mt-1 mr-1 mb-1" 
              />
              <span className="text-[20px]">M.Fk</span>
            </div>
            <ul className="flex space-x-4 mt-4 mb-2 md:mt-0">
              <li><Link href="/" className="hover:text-black hover:bg-white p-2 rounded-md">Home</Link></li>
              <li><Link href="/about" className="hover:text-black hover:bg-white p-2 rounded-md">About</Link></li>
              <li><Link href="/projects" className="hover:text-black hover:bg-white p-2 rounded-md">Projects</Link></li>
              <li><Link href="/contact" className="hover:text-black hover:bg-white p-2 rounded-md">Contact</Link></li>
            </ul>
          </nav>
        </header>
        <main className="flex-grow container mx-auto p-4">
          {children}
        </main>
        <footer className="bg-black text-white p-4 text-center w-full">
          <p>© 2024 My Website</p>
        </footer>
      </body>
    </html>
  );
};

export default Layout;



